<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\fonts\Inter.ttc" />
    <None Remove="assets\fonts\InterVariable.ttf" />
    <None Remove="assets\fonts\Kingthings Petrock light.ttf" />
    <None Remove="assets\fonts\Kingthings Petrock.ttf" />
    <None Remove="assets\fonts\MagicCardsNormal.ttf" />
    <None Remove="assets\fonts\TrajanusBricks.ttf" />
    <None Remove="assets\fonts\TrajanusBricksXtra.ttf" />
    <None Remove="assets\fonts\TrajanusBriX-Invers.ttf" />
    <None Remove="assets\images\0\list.png" />
    <None Remove="assets\images\0\top.png" />
    <None Remove="assets\images\1\list.png" />
    <None Remove="assets\images\1\top.png" />
    <None Remove="assets\images\2\list.png" />
    <None Remove="assets\images\2\top.png" />
    <None Remove="assets\images\3\list.png" />
    <None Remove="assets\images\3\top.png" />
    <None Remove="assets\images\4\list.png" />
    <None Remove="assets\images\4\top.png" />
    <None Remove="assets\images\5\list.png" />
    <None Remove="assets\images\5\top.png" />
    <None Remove="assets\images\6\list.png" />
    <None Remove="assets\images\6\top.png" />
    <None Remove="assets\images\skyrimList.png" />
    <None Remove="assets\images\top.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" Version="3.2.1" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Json" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\fonts\Inter.ttc">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\fonts\InterVariable.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\fonts\MagicCardsNormal.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\images\0\list.png" />
    <Resource Include="assets\images\0\top.png" />
    <Resource Include="assets\images\1\list.png" />
    <Resource Include="assets\images\1\top.png" />
    <Resource Include="assets\images\2\list.png" />
    <Resource Include="assets\images\2\top.png" />
    <Resource Include="assets\images\3\list.png" />
    <Resource Include="assets\images\3\top.png" />
    <Resource Include="assets\images\4\list.png" />
    <Resource Include="assets\images\4\top.png" />
    <Resource Include="assets\images\5\list.png" />
    <Resource Include="assets\images\5\top.png" />
    <Resource Include="assets\images\6\list.png" />
    <Resource Include="assets\images\6\top.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>SimpleLoadOrderOrganizer.Resources</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
