//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAZOR.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RAZOR.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Check for conflicts.
        /// </summary>
        public static string checkForConflicts {
            get {
                return ResourceManager.GetString("checkForConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for conflicts....
        /// </summary>
        public static string checkingForConflicts {
            get {
                return ResourceManager.GetString("checkingForConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file.
        /// </summary>
        public static string configFile {
            get {
                return ResourceManager.GetString("configFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts.
        /// </summary>
        public static string conflicts {
            get {
                return ResourceManager.GetString("conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©-2025-KARYUUDO-DIGITAL.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}, please choose the correct file..
        /// </summary>
        public static string correctFileNotFound {
            get {
                return ResourceManager.GetString("correctFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}, please choose the correct directory..
        /// </summary>
        public static string couldNotFindDirectory {
            get {
                return ResourceManager.GetString("couldNotFindDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Edit masters.
        /// </summary>
        public static string editMasters {
            get {
                return ResourceManager.GetString("editMasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} executable..
        /// </summary>
        public static string exeNotFound {
            get {
                return ResourceManager.GetString("exeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the game..
        /// </summary>
        public static string failedToLaunchError {
            get {
                return ResourceManager.GetString("failedToLaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading config file, creating new one....
        /// </summary>
        public static string fileError {
            get {
                return ResourceManager.GetString("fileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid path for the game directory..
        /// </summary>
        public static string gameDirectoryError {
            get {
                return ResourceManager.GetString("gameDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light plugin.
        /// </summary>
        public static string lightPlugin {
            get {
                return ResourceManager.GetString("lightPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading-plugins....
        /// </summary>
        public static string loadingPlugins {
            get {
                return ResourceManager.GetString("loadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string master {
            get {
                return ResourceManager.GetString("master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters.
        /// </summary>
        public static string masters {
            get {
                return ResourceManager.GetString("masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override records.
        /// </summary>
        public static string overrideRecords {
            get {
                return ResourceManager.GetString("overrideRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid path for the plugin config file..
        /// </summary>
        public static string pluginConfigError {
            get {
                return ResourceManager.GetString("pluginConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently active game&apos;s settings/load order will be saved. Do you want to save every games&apos; settings/load order?.
        /// </summary>
        public static string saveDialogue {
            get {
                return ResourceManager.GetString("saveDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving config file, this may be because the file is open in another program, or that this program wasn&apos;t ran as administrator....
        /// </summary>
        public static string saveError {
            get {
                return ResourceManager.GetString("saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script extender detected.
        /// </summary>
        public static string scriptExtenderDetected {
            get {
                return ResourceManager.GetString("scriptExtenderDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZOR has detected a script extender, do you want to launch {0} via the script extender?.
        /// </summary>
        public static string scriptExtenderPrompt {
            get {
                return ResourceManager.GetString("scriptExtenderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter-valid-paths-for-the-game-folder-and-the-plugin-config-file,-or-persist-in-the-doomed-world-you-have-created.-(The-plugin-config-file-is-usually-called-&quot;plugins.txt&quot;-and-is-located-in-the-local-folder-in-the-AppData-directory.-In-Morrowind&apos;s-case,-active-plugins-are-recorded-in-Morrowind.ini-in-the-game-directory..
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
